repos:
  - repo: local
    hooks:
      - id: checkstyle
        name: Checkstyle
        entry: ./run-checkstyle.sh
        language: script
        files: \.java$

  # - repo: https://github.com/thoughtworks/talisman
  #   rev: "v1.31.0"
  #   hooks:
  #   - id: talisman-commit
  #     name: talisman
  #     entry: talisman --githook pre-commit -p **/*.java