repos:
  - repo: local
    hooks:
      - id: checkstyle
        name: Checkstyle
        entry: ./run-precommit-checks.sh checkstyle
        language: script
        files: \.java$

  - repo: local
    hooks:
      - id: talisman
        name: Talisman
        entry: ./run-precommit-checks.sh talisman
        language: script
        files: .*
        # entry: talisman --githook pre-commit -p **/*.java
